### ISSUE TITLE
choc_WebView.h missing <functional>  (minor issue)

### ISSUE THREAD

**Issue by dbadb** [Tracktion/choc#10]
Minor issue:  compiling trivial example which includes "choc/gui/choc_WebView.h" fails with:

`choc_WebView.h(92): error C2039: 'function': is not a member of 'std'`

Simple workaround is to `#include <functional>` prior to webview, but choc_WebView.h  (and others perhaps) should include it. 

The example test (main.cpp) hides this issue because it includes the kitchen sink (via choc_tests.h).

**Comment by julianstorer** [comment]
Thanks! I've pushed a fix for that now
