### ISSUE TITLE
no mutex ≠ lock-free

### ISSUE THREAD

**Issue by lfnoise** [Tracktion/choc#11]
```DirtyList::markAsDirty()``` is not lock-free because ```SingleReaderMultipleWriterFIFO::push()``` is not lock-free. Lock-free does not mean that you don't use a mutex, it means that there is no condition where all threads are blocked and none can make progress. 

If thread A calls ```SingleReaderMultipleWriterFIFO::push()```, locks the SpinLock and is then suspended by the thread scheduler to switch to thread B, which then also calls  ```SingleReaderMultipleWriterFIFO::push()```, both threads will be blocked for the as long as thread B is scheduled. If the thread scheduler then goes on to schedule thread C, which also tries to push the queue, then three threads are blocked on the SpinLock. And similarly for threads D and beyond. No threads are making progress. It doesn't matter that this is unlikely. If it can happen, it is not lock-free. 

See [https://preshing.com/20120612/an-introduction-to-lock-free-programming/](https://preshing.com/20120612/an-introduction-to-lock-free-programming/)

**Comment by julianstorer** [comment]
Right - I'm just going to clarify the docs to avoid anyone else nit-picking the same technicality, but don't think I'll change the code.

If there's only one thread calling markAsDirty() (which is how I was using the class) then it is lock-free.. You'd need to have multiple realtime threads all hammering markAsDirty() at the same time for the lock to actually ever get contested. Given that it's far from trivial to make the writing fully lock-free, then that's not something I'd want to spend time on when there's a chance nobody will ever need it.
