### ISSUE TITLE
creating javascript class from c++ (quickjs)

### ISSUE THREAD

**Issue by mightgoyardstill** [Tracktion/choc#15]
loving the choc library! just came across your recent adc talk.

i was wondering if its possible to register classes/objects via choc into our javascript engines?

i've seen you've got a registerFunction but nothing along the lines of a registerClass?

currently using the barebones quickjs library you can register a class like this: https://github.com/bellard/quickjs/blob/master/examples/point.c

wasn't too sure if i missed something?

**Comment by mightgoyardstill** [comment]
ah! so in your case you're just creating your classes via javascript instead of internally on the c++ side? (just reiterating incase i misunderstood anything).

makes sense if so, i guess it clearly defines your javascript API while maintaining a cleaner and simpler project code base.

is there anything thats stopping you from calling these methods as global functions outside of their respective classes?

**Comment by julianstorer** [comment]
Yeah, it just seemed simpler to keep the library code small, and not have to implement objects for both QuickJS and Duktape (if it's even possible in duktape)

No, nothing to stop them being called, other than their names being pretty obscure.

**Comment by mightgoyardstill** [comment]
so i've managed something i GUESS is ok, i don't like having to include static JSValue functions in my classes but it seems to be the most cleanest way i could manage in this use case. just thought i'd share incase you were interested (feel free to close this issue now!)

```
class NativeFunctionBindings {
public:
    void registerMethod(const char* name, int nargs, JSCFunction *func)
    {
        std::cout << "registerMethod called.\n"; // Debug
        jsMethods.push_back(JS_CFUNC_DEF(name, static_cast<uint8_t>(nargs), func));
    }

    const JSCFunctionListEntry* getJSMethods() const
    {
        std::cout << "getJSMethods called.\n"; // Debug
        return jsMethods.data();
    }

    size_t getJSMethodsCount() const 
    {
        std::cout << "getJSMethodsCount called.\n"; // Debug
        return jsMethods.size();
    }
    
protected:
    std::vector<JSCFunctionListEntry> jsMethods;
};


template <typename T>
struct NativeClassBinding
{
    static JSClassID js_class_id;
    static JSClassDef js_class_def;
    static std::vector<JSCFunctionListEntry> jsMethods;

    static JSValue js_constructor(JSContext *ctx, JSValueConst new_target, int argc, JSValueConst *argv)
    {
        std::cout << "JS Constructor called.\n"; // Debug

        JSValue obj = JS_NewObjectClass(ctx, js_class_id);

        T* native_obj = new T();

        std::cout << "Native object created.\n"; // Debug

        JS_SetOpaque(obj, native_obj);
        return obj;
    }

    static void js_finalizer(JSRuntime *rt, JSValue val) 
    {
        T* native_obj = (T*)JS_GetOpaque(val, js_class_id);

        if (native_obj) 
        {
            delete native_obj;
        }
    }

    static void registerMethod(const char* name, int nargs, JSCFunction *func)
    {
        std::cout << "Registering Method: " << name << ".\n"; // Debug

        jsMethods.push_back( {name, JS_PROP_WRITABLE | JS_PROP_CONFIGURABLE, JS_DEF_CFUNC, 0, .u = { .func = { static_cast<uint8_t>(nargs), JS_CFUNC_generic, { .generic = func } } }});
    }

    static void ClassRegister(JSContext* ctx, const char* name, int ctorArgs = 0, int magic = 0) 
    {
        std::cout << "Registering class: " << name << ".\n"; // Debug

        JS_NewClassID(&js_class_id);

        js_class_def.class_name = name;
        js_class_def.finalizer = js_finalizer;

        JS_NewClass(JS_GetRuntime(ctx), js_class_id, &js_class_def);

        JSValue global_obj, js_class, proto;

        global_obj = JS_GetGlobalObject(ctx);

        proto = JS_NewObject(ctx);

        js_class = JS_NewCFunction2(
            ctx, js_constructor, name, ctorArgs, JS_CFUNC_constructor, magic);

        JS_SetPropertyFunctionList(
            ctx, proto, jsMethods.data(), jsMethods.size());

        JS_SetConstructor(ctx, js_class, proto);
        JS_SetClassProto(ctx, js_class_id, proto);

        JS_SetPropertyStr(ctx, global_obj, name, js_class);
        JS_FreeValue(ctx, global_obj);
    }
};

template <typename T>
JSClassID NativeClassBinding<T>::js_class_id;

template <typename T>
JSClassDef NativeClassBinding<T>::js_class_def;

template <typename T>
std::vector<JSCFunctionListEntry> NativeClassBinding<T>::jsMethods;

template <typename T>
void registerNativeClass(JSContext* ctx, const char* name, int ctorArgs = 0, int magic = 0)
{
    std::cout << "Registering native class: " << name << ".\n"; // Debug

    T::registerJSMethods();
    NativeClassBinding<T>::ClassRegister(ctx, name, ctorArgs, magic);
}

class Foo : public NativeFunctionBindings
{
public:
    Foo() { std::cout << "Foo() constructor called.\n"; }
    ~Foo() { std::cout << "~Foo() destructor called.\n"; }

    void thisMethod()
    {
        std::cout << "Foo:: this method called\n";
    }
    void thatMethod()
    {
        std::cout << "Foo:: that method called\n";
    }

    static JSValue js_this_method(
        JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) 
    {
        Foo *native_obj = (Foo*)JS_GetOpaque2(
            ctx, this_val, NativeClassBinding<Foo>::js_class_id);

        if (!native_obj)
            return JS_EXCEPTION;

        native_obj->thisMethod();
        return JS_UNDEFINED;
    }

    static JSValue js_that_method(
        JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) 
    {
        Foo *native_obj = (Foo*)JS_GetOpaque2(
            ctx, this_val, NativeClassBinding<Foo>::js_class_id);

        if (!native_obj)
            return JS_EXCEPTION;

        native_obj->thatMethod();
        return JS_UNDEFINED;
    }


    static void registerJSMethods()
    {
        std::cout << "Registering JS methods.\n"; // Debug

        NativeClassBinding<Foo>::registerMethod("thisMethod", 0, js_this_method);
        NativeClassBinding<Foo>::registerMethod("thatMethod", 0, js_that_method);
    }
};


int main() 
{
    JSRuntime *rt;
    JSContext *ctx;

    rt = JS_NewRuntime();
    ctx = JS_NewContext(rt);

    registerNativeClass<Foo>(ctx, "Foo");

    std::string js_code =
    R"(
        'use strict';
        var fooObj = new Foo();
        fooObj.thisMethod();
        fooObj.thatMethod();
    )";

    JSValue val = JS_Eval(
        ctx, js_code.c_str(), js_code.length(), "<input>", JS_EVAL_TYPE_GLOBAL);

    if (JS_IsException(val))
    {    
        js_std_dump_error(ctx);
    }

    JS_FreeValue(ctx, val);

    JS_FreeContext(ctx);
    JS_FreeRuntime(rt);

    return 0;
}
```

**Comment by julianstorer** [comment]
Yes, that's probably the best you can do, but still ends up being at least as much code as the way I've been doing things with JS helper classes!

I'm going to park this issue, but thanks, has been interesting!

**Comment by mightgoyardstill** [comment]
sorry to keep going on about this, i'm finally getting round to trying out your method of creating a javascript api using choc and was hoping i could ask a couple questions..

you mentioned that forwarding method calls to global functions worked fine for your use-case, and it helped to keep the library code small?

i guess i'm just curious on what type of stuff you would choose to register as global functions, and then what it might look like for you making your javascript class with them? (especially if you're using obscure names!)

i've also been trying to dig into the cmajor source code to see if it has any hints to this but i can't seem to find too much!

my naive approach would be something like this, where anything prefixed with "_" is a global registered function but my obsessive compulsiveness still hates this lol:
```
class Window
{
    constructor(name, x, y, width, height)
    {
        _setPosition (x, y, width, height);
        _setTitle (name);
        _setResizeable (false);
        _setMinimumSize (width, height);
        _setMaximumSize (1500, 1200);
    }
    toFront()
    {
        _toFront();
    }
};
```

once again sorry for bringing this up again, just want to know what the best practice would be for something like this

**Comment by mightgoyardstill** [comment]
the ONE thing i've noticed in cmajor is that a lot of the javascript classes extend HTMLElement! i'm gonna take a shot in the dark and assume thats where a lot of those global functions are?

**Comment by julianstorer** [comment]
I think you're getting a bit muddled there - HTMLElement is part of the browser javascript runtime, none of which is available in an embedded JS engine. The code you're referring to must be our web UI code, not something that we run with QuickJS.

**Comment by mightgoyardstill** [comment]
yeah i definitely am, i just assumed there were some parts of cmajor that had quickjs embedded to communicate between the web code and the c++ source. so when you're embedding quickjs and making a bunch of classes are you doing something along the lines of what i'm doing there?

to be a bit more specific on my use cases i'm trying to do plugin hosting and basic "canvas" type stuff via scripting. i originally managed it through the first method i shown you but it made the code base so messy so wondered if your way would make life easier

**Comment by julianstorer** [comment]
No.. that's not how it works. If you're running code in a browser, you need to add bindings to the webview, there's no QuickJS involved because the engine is the one in the browser. 
In Cmajor we use QuickJS for a totally different purpose - running test scripts on the command line.

**Comment by julianstorer** [comment]
Yep, that's right.
