### ISSUE TITLE
linux warnings for webview (low priority)

### ISSUE THREAD

**Issue by dbadb** [Tracktion/choc#16]
I noticed this warning when compiling choc/tests/main.cpp on Debian 11 (bullseye).. I briefly looked into the web_view_evaluate_javascript approach and the change appears non-trivial, though quite doable I'm sure.  Functions just fine when compiled with the warning.

btw: this choc thing is, well, classy! (thanks for the creation).

```
../gui/choc_WebView.h: In member function ‘void choc::ui::WebView::Pimpl::evaluateJavascript(const string&)’:
../gui/choc_WebView.h:262:105: warning: ‘void webkit_web_view_run_javascript(WebKitWebView*, const gchar*, GCancellable*, GAsyncReadyCallback, gpointer)’ is deprecated: Use 'webkit_web_view_evaluate_javascript' instead [-Wdeprecated-declarations]
  262 |         webkit_web_view_run_javascript (WEBKIT_WEB_VIEW (webview), js.c_str(), nullptr, nullptr, nullptr);
         |                                                                                                      ^
```

**Comment by julianstorer** [comment]
Thanks - though doing a bit of research it sounds like this is very newly-deprecated, and people will be using the old SDK and have the old webkit installed for quite a while, so I think I might leave this for a while. (That seems to be what the maintainers of other projects are doing).
