### ISSUE TITLE
webview reports an older version of browser.

### ISSUE THREAD

**Issue by Dadi100** [Tracktion/choc#19]
Hi,
Using choc::ui::WebKit on Mac, several sites are reporting that I'm using an older version of browser (e.g. youtube), and other sites are even refusing to load.

I found that the user agent is reporting the following:
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)"
while Safari application (which works fine) is reporting the following:
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15"

I'm using Mac mini, M2, Ventura 13.3.
What is the right way to resolve this?
Thank you.

**Comment by julianstorer** [comment]
Well, I don't think there's anything *wrong* with the behaviour it's got there - it's not reporting that it's Safari, because it isn't Safari, so that makes sense and I don't think I'd want to deliberately make it pretend to be Safari.

I would be open to adding something to WebView that'd let you give it a user agent string to report, so that you could make the decision yourself to either give the real name of your app, or to bodge in a fake "Safari" name if that's what you need. Haven't got time to look at adding this feature right now (which would of course also need to be implemented for Windows and Linux too) but it shouldn't be hard if all the APIs provide a user-agent string option

**Comment by Dadi100** [comment]
For the target website I need to navigate to I'm getting a message that the browser I'm using is not supporting their features (it is using webrtc, camera and more) and I'm prompt to use Chrome or Firefox.
I would prefer to avoid dealing with user agent or similar stuff, at least if possible. Maybe there a way to configure the webkit so it will support latest browser features?
BTW on Windows this is working flawless.
What are my options?

**Comment by julianstorer** [comment]
I'm not sure what else you think I could suggest here - clearly it's already reporting its webkit version as being the latest one. I don't know of any secret feature enable/disable flags that could be turned on..

**Comment by Dadi100** [comment]
OK, thanks anyway.

**Comment by julianstorer** [comment]
If you want to go digging around the WebKit API and find something, let me know!

**Comment by Dadi100** [comment]
For reference, this is the URL I failed to show using webview:  "https://meet.jit.si/"
I also found out that using other libraries gives the same result.

**Comment by julianstorer** [comment]
No surprise there, all libraries will use the same embedded browser. 
Bear in mind that these things aren't really intended for showing random webpages, the main reason anyone would embed a browser is to display their own web content, so this won't matter.

**Comment by Dadi100** [comment]
You wrote above about the possibility of adding support for specifying a custom user agent.
Meantime, is it possible to modify the existing code just for Mac to specify it? If yes, can you please point me to the right place in code and I'll try to take it from there?
Thank you.

**Comment by julianstorer** [comment]
I've not researched it yet, so have no idea how it'd be done. It's probably a one-liner, the hard bit is just finding the right API to use.

**Comment by otristan** [comment]
I've made the modidication in order to support custom user agent

Untested on Windows and Linux :)
[userAgent.txt](https://github.com/Tracktion/choc/files/12717148/userAgent.txt)

**Comment by julianstorer** [comment]
Thanks! Looks pretty sensible, I'll get that rolled in shortly.. :)

**Comment by otristan** [comment]
typo in your commit

        if ( options.customUserAgent.empty())
            call<void> (webview, "setValue:forKey:", getNSString (options.customUserAgent), getNSString ("customUserAgent"));

should be

        if ( !options.customUserAgent.empty())
            call<void> (webview, "setValue:forKey:", getNSString (options.customUserAgent), getNSString ("customUserAgent"));

**Comment by julianstorer** [comment]
oh damn.. Thanks, will push a fix!

**Comment by otristan** [comment]
Looks like user agent has issues on Windows as it's only set up in onResourceRequestedand not in Navigate

**Comment by otristan** [comment]
I probably miss the extra miles

Basically you need to define those struct

```
MIDL_INTERFACE("e562e4f0-d7fa-43ac-8d71-c05150499f00")
ICoreWebView2Settings : public IUnknown
{
public:
  virtual HRESULT STDMETHODCALLTYPE get_IsScriptEnabled(BOOL * isScriptEnabled) = 0;
  virtual HRESULT STDMETHODCALLTYPE put_IsScriptEnabled(BOOL isScriptEnabled) = 0;
  virtual HRESULT STDMETHODCALLTYPE get_IsWebMessageEnabled(BOOL* isWebMessageEnabled) = 0;
  virtual HRESULT STDMETHODCALLTYPE put_IsWebMessageEnabled(BOOL isWebMessageEnabled) = 0;
  virtual HRESULT STDMETHODCALLTYPE get_AreDefaultScriptDialogsEnabled(BOOL* areDefaultScriptDialogsEnabled) = 0;
  virtual HRESULT STDMETHODCALLTYPE put_AreDefaultScriptDialogsEnabled(BOOL areDefaultScriptDialogsEnabled) = 0;
  virtual HRESULT STDMETHODCALLTYPE get_IsStatusBarEnabled(BOOL* isStatusBarEnabled) = 0;
  virtual HRESULT STDMETHODCALLTYPE put_IsStatusBarEnabled(BOOL isStatusBarEnabled) = 0;
  virtual HRESULT STDMETHODCALLTYPE get_AreDevToolsEnabled(BOOL* areDevToolsEnabled) = 0;
  virtual HRESULT STDMETHODCALLTYPE put_AreDevToolsEnabled(BOOL areDevToolsEnabled) = 0;
  virtual HRESULT STDMETHODCALLTYPE get_AreDefaultContextMenusEnabled(BOOL* enabled) = 0;
  virtual HRESULT STDMETHODCALLTYPE put_AreDefaultContextMenusEnabled(BOOL enabled) = 0;
  virtual HRESULT STDMETHODCALLTYPE get_AreHostObjectsAllowed(BOOL* allowed) = 0;
  virtual HRESULT STDMETHODCALLTYPE put_AreHostObjectsAllowed(BOOL allowed) = 0;
  virtual HRESULT STDMETHODCALLTYPE get_IsZoomControlEnabled(BOOL* enabled) = 0;
  virtual HRESULT STDMETHODCALLTYPE put_IsZoomControlEnabled(BOOL enabled) = 0;
  virtual HRESULT STDMETHODCALLTYPE get_IsBuiltInErrorPageEnabled(BOOL* enabled) = 0;
  virtual HRESULT STDMETHODCALLTYPE put_IsBuiltInErrorPageEnabled(BOOL enabled) = 0;
};

MIDL_INTERFACE("ee9a0f68-f46c-4e32-ac23-ef8cac224d2a")
ICoreWebView2Settings2 : public ICoreWebView2Settings
{
public:
    virtual HRESULT STDMETHODCALLTYPE get_UserAgent(LPWSTR * userAgent) = 0;
    virtual HRESULT STDMETHODCALLTYPE put_UserAgent(LPCWSTR userAgent) = 0;
};
```
and then in createEmbeddedWebView

```
 if (!customUserAgent.empty())
                    {
                      ICoreWebView2Settings* settings;
                      coreWebView->get_Settings(&settings);

                      ICoreWebView2Settings2* settings2;

                      settings->QueryInterface(&settings2);

                      if (settings2 != nullptr)
                      {
                        const auto agent = createUTF16StringFromUTF8(customUserAgent);
                        settings2->put_UserAgent(agent.c_str());
                      }
                    }
```

But weirdly settings2 is nullptr

**Comment by otristan** [comment]
Good thing is that it will allow to support enableDebugMode on Windows
 settings->put_AreDevToolsEnabled(enableDebugMode);

**Comment by otristan** [comment]
Where did you get your GUID for each class ?
The one you use don't match the one I find in the Windows SDK, so I suppose this is the issue here.

Thanks !

**Comment by otristan** [comment]
See mods here
https://github.com/otristan/choc/commit/39460812129e686401ec7666f774255c9c0ac3b7

**Comment by julianstorer** [comment]
Thanks Olivier, I'll look through all this asap!

**Comment by julianstorer** [comment]
I've grabbed the latest version of the DLLs now and updated it all.. took a bit more wrangling than you had in your changes to make it work on mingw and arm, but seems to be passing my tests now. Would appreciate you checking if the latest develop branch works for whatever your use-case was.

**Comment by otristan** [comment]
It works perfect in your version as well now. Thanks !
