### ISSUE TITLE
WebView warnings

### ISSUE THREAD

**Issue by otristan** [Tracktion/choc#22]
Hi,

Using the webview module in a Juce application, I get some report in Xcode log view when closing the app.
```

objc[5483]: objc_disposeClassPair: class 'CHOCWebView_3566101704' still has subclasses, including 'NSKVONotifying_CHOCWebView_3566101704'!
objc[5483]: objc_disposeClassPair: class 'CHOCWebView_3566101704' still has subclasses, including 'NSKVONotifying_CHOCWebView_3566101704'!
```

Are those normal ? Or did forgot to clean something ?

Thanks !

**Comment by julianstorer** [comment]
Yes, they're really annoying - something in the objC key-value observer system is creating hidden subclasses of these classes, and hanging onto them until shutdown. I think to avoid the warning I'll add something that just leaks the class, as there doesn't seem to be any other option to make it outlive the thing that's using it.
