### ISSUE TITLE
DesktopWindow is dependant on Webkit/WebView? (Mac)

### ISSUE THREAD

**Issue by mightgoyardstill** [Tracktion/choc#28]
is there anything in particular which the desktop window is relying on in Webkit? From looking in the source I can't seem to see anything glaringly obvious but I run into this when I try and use it without WebView

```
#else
 #error "choc WebView only supports OSX, Windows or Linux!"
#endif
```

**Comment by julianstorer** [comment]
Sorry, there's a typo in that line - obviously it should say ` #error "choc DesktopWindow only supports OSX, Windows or Linux!"`

..and the file should also include choc_Platform.h so it can correctly tell what OS it is. I guess I've never used this file on its own before! All easy to fix - will push something in a moment..

**Comment by mightgoyardstill** [comment]
ok thanks! i was also experimenting the other week with a custom graphics class i’m working on and when i tried to build and run the project without including Webkit the DesktopWindow wouldn’t work.

I can’t remember the issue i was getting from the top of my head but will look into it when i next get a chance!
