### ISSUE TITLE
Bug with intToFloatScaleFactor for FLAC format

### ISSUE THREAD

**Issue by azeteg** [Tracktion/choc#29]
In `choc_AudioFileFormat_FLAC.h`, in the function `handleStreamInfo` there is a line:

`intToFloatScaleFactor = 1.0 / ((1u << (31u - info.bits_per_sample)) - 1);`

could it be that you wanted this to be:
`intToFloatScaleFactor = 1.0 / ((1u << (info.bits_per_sample - 1)) - 1);`

Cheers, Martin

**Comment by julianstorer** [comment]
Yes! Thankyou for spotting and reporting that! Pushing a fix now...
