### ISSUE TITLE
Hi Julian

### ISSUE THREAD

**Issue by jacquesmignault** [Tracktion/choc#30]
Hi Julian. Jacques, from JUCE world.
I'm using your browser component. Very slick.
evaluateJavascript, I'm wondering what does that do really ?
Is it a function to run some javascript in the browser, directly from C++ ?
Perhaps it is food for thought....

**Comment by julianstorer** [comment]
Thanks, but I don't think I understand what you're asking? 

Like the name suggests, evaluateJavascript() does indeed run some javascript in the browser.. And obviously it's directly from C++ because.. what else could a C++ function possibly do..!?

**Comment by jacquesmignault** [comment]
OK thank you very much for your advice :-)
Cheers
