### ISSUE TITLE
linux webview debugger

### ISSUE THREAD

**Issue by dbadb** [Tracktion/choc#32]
Here are two lines required to enable the web developer inspector under gtk WebKit:

```c++
WebKitWebInspector *inspector = webkit_web_view_get_inspector (WEBKIT_WEB_VIEW(webview));
webkit_web_inspector_show (WEBKIT_WEB_INSPECTOR(inspector));
```

I placed these two lines around line 196 of choc_WebView.h and am happily debugging.

**Comment by julianstorer** [comment]
Thanks - that's a useful tip, but I'm not sure it'd be the right thing to force it to appear programmatically like that.. Doesn't it have a right-click menu that lets the user choose to show the inspector?

**Comment by dbadb** [comment]
In my admittedly cursory investigations, I wasn't able to discover any magic keystrokes as exist on windows and macos.
