### ISSUE TITLE
WebView file input support

### ISSUE THREAD

**Issue by blinthicum** [Tracktion/choc#34]
Hey there! 

Been enjoying working with the choc WebView on OSX, but I can't seem to get the file picker dialogue to pop up for the html file input, e.g.

```html
<input type="file" />
```

Is this something that is supported currently? Or will I have to use JUCE's FileChooser as a work around and do this on the backend?

Thanks in advance!

**Comment by julianstorer** [comment]
This was a bit hairy, but I've got something going - try the develop branch and see if it works for you...

**Comment by blinthicum** [comment]
Wow, thanks for the quick turnaround! This appears to work for me! Nice!
