### ISSUE TITLE
Compatibility with older versions of WebKit on MacOS?

### ISSUE THREAD

**Issue by daveboulden** [Tracktion/choc#36]
Just a question: is `choc/gui/choc_WebView.h` compatible with older versions of WebKit on MacOS? 

If not, how far back does the compatibility go? Only asking as I have some strange issues with someone trying to run some of my code on Monterey 12.7.2 with WebKit v17617. I'm not seeing the same issue with the same binary on my Ventura 13.4.1 Mac mini, nor with the cross-platform Windows version of the same code that is using the embedded MS WebView2

**Comment by julianstorer** [comment]
I don't know all the details of how WebKit has changed over previous versions of OSX, but I'd be surprised if it didn't work on fairly recent ones like Monterey. Do you have any clues about what the nature of the problem is?

**Comment by daveboulden** [comment]
It seems to be mostly a binding not working (binding a C++ function to a button click in the web page) and I'm experiencing some very weird anomalies displaying a Bootstrap CSS styled UL list which hides itself when none of it's list items have any text wrap - though I think that's more of a WebKit oddity than anything to do with `choc` 'cos that same styling works perfectly on Windows - my next step there will be to test it standalone in Safari.
I may have to send a debug version to the customer so that he can send me details from the Developer Tools console to see if there are any errors - I'm seeing no errors in the console under Ventura (or Windows) using the same binary and web-page data.

**Comment by julianstorer** [comment]
Hmm, tricky because there are so many steps at which something like that could be going wrong. Keep me posted if you find any clues..

**Comment by daveboulden** [comment]
It is very much looking like the issues I am seeing are directly related to the version of WebKit present on the machine running my code. I seem to have cleared all issues with the code running under Sonoma, but users are still seeing issues under Monterey and Sonoma... so I think it is all due to the combination of what I am doing in my CSS & JS and what that each version of WebKit will support.

**Comment by julianstorer** [comment]
Yep, that sounds likely to me. I'm not much of a web-dev, but I assume there must be tools out there that help test webpages under different browser versions..
