### ISSUE TITLE
Real life example of choc_COM.h?

### ISSUE THREAD

**Issue by yyokyfo** [Tracktion/choc#37]
Everything I can find is https://github.com/Tracktion/choc/blob/main/tests/choc_tests.h#L2198, but it's a test, not a real life example.

**Comment by julianstorer** [comment]
I used it for the Cmajor COM interfaces here: https://github.com/SoundStacks/cmajor/tree/main/include/cmajor/COM
HTH!

**Comment by yyokyfo** [comment]
> I used it for the Cmajor COM interfaces here: https://github.com/SoundStacks/cmajor/tree/main/include/cmajor/COM HTH!

I'm sorry but I can't find any UUIDs! Please correct me if I'm wrong. Thank you.

**Comment by julianstorer** [comment]
It doesn't do UUIDs or any of the QueryInterface stuff that things like Windows use. It's just for ref-counting and passing object interfaces across DLL boundaries for use in APIs, etc.
