### ISSUE TITLE
Fix: ‘auto’ deduced as ‘id’ Xcode warning

### ISSUE THREAD

**Issue by geraintluff** [Tracktion/choc#41]
I'm using Xcode 13.2.1, and I get a warning when `auto` is deduced as `id`.  This is [on by default](https://clang.llvm.org/docs/DiagnosticsReference.html#wauto-var-id) in Clang.

This can be fixed by replacing `auto` with `id` in `choc_WebView.h`.  This matches [`choc_MessageLoop.h`](https://github.com/Tracktion/choc/blob/d029a8376adb09ecca89e0ddd87725376d8bf632/gui/choc_MessageLoop.h#L273C5-L273C30), which is the only other place `call<id>` is used to initialise a variable.

<img width="257" alt="Screenshot 2024-01-28 at 13 32 17" src="https://github.com/Tracktion/choc/assets/1957191/e37b9df2-0891-4a17-9583-c398e67aee62">

-----

I originally opened this as PR #40, but since PRs are complicated by copyright issues, you can find the locations yourself with the RegEx `auto .* = call<id>`:

```bash
find . -iname \*.h -exec grep -Hn -i "auto .* = call<id>" {} \;
```

**Comment by julianstorer** [comment]
Thanks for the heads-up, I'll update my tests to the latest clang and make sure that warning is turned on!
