### ISSUE TITLE
WebView feature suggestion: custom URI scheme and resource domain

### ISSUE THREAD

**Issue by awood314** [Tracktion/choc#48]
When using the WebView with the `fetchResource` option, we get blocked by CORS security protection when web resources make HTTP requests to our back-end services. In order to be deliberate about what origin those services see and allow, something we've implemented in our fork is the ability to override the components of the URI scheme:
- on Mac, the `choc://` application URI scheme and `choc.choc` domain
- on Windows, the `choc.localhost` domain

This doesn't implement Linux, but just thought I'd drop it here in case you may find it useful: https://github.com/splice/choc/pull/1

Thanks!

**Comment by julianstorer** [comment]
Hi Alex

Someone else had a similar problem and we solved it with this commit:
https://github.com/Tracktion/choc/commit/77c6a89a9f2913169fb33e4857ee9d54844661dd

Does that work for you?

**Comment by dbadb** [comment]
I have a change in my branch that supports a user-provided options customUriScheme,  customUriHome (following the pattern of userAgent) to specify the scheme and domain.   Change was quite simple and can be seen here:

https://github.com/cannerycoders/choc/commit/3fe379c44f1c8bbbe98bb5a505889ee0433a5532

I originally implemented it as an #ifdef, but found the need for multiple schemes within the same runtime.

**Comment by julianstorer** [comment]
I've implemented this with a few differences, but should do what you need. Let me know if it gives you any trouble..
