### ISSUE TITLE
choc_MessageLoop.h does not compile with clang++ -std=c++2b or -std=c++23

### ISSUE THREAD

**Issue by atsushieno** [Tracktion/choc#58]
I have been trying to use `choc::messageloop` functions in my project, and noticed that it does not compile if I specify `CMAKE_CXX_STANDARD 23` in my CMake project. CMake (3.29.6 when I use CLion) resolves that `23` to `-std=c++2b`. That is, choc does not compile with the combination of the latest CMake, clang++, and C++23.

This is the actual compilation error (on macos here):

```
/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/usr/include/c++/v1/__memory/unique_ptr.h:64:19: error: invalid application of 'sizeof' to an incomplete type 'choc::messageloop::Timer::Pimpl'
   64 |     static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete type");
      |                   ^~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/usr/include/c++/v1/__memory/unique_ptr.h:266:7: note: in instantiation of member function 'std::default_delete<choc::messageloop::Timer::Pimpl>::operator()' requested here
  266 |       __ptr_.second()(__tmp);
      |       ^
/Users/atsushi/sources/uapmd/external/remidy/../../external/choc/choc/gui/choc_MessageLoop.h:101:49: note: in instantiation of member function 'std::unique_ptr<choc::messageloop::Timer::Pimpl>::reset' requested here
  101 |         void clear()                    { pimpl.reset(); }
      |                                                 ^
/Users/atsushi/sources/uapmd/external/remidy/../../external/choc/choc/gui/choc_MessageLoop.h:108:16: note: forward declaration of 'choc::messageloop::Timer::Pimpl'
  108 |         struct Pimpl;
      |                ^
1 error generated.
```

The reference to `pimpl::reset()` requires `pimpl` to be complete. After some discussion at community (TAP #cplusplus) we figured that it should not have compiled even with earlier `-std` versions in the first place.

A simple fix is to define `clear()` outside `Timer` class declaration. https://gist.github.com/atsushieno/139e200beaba93398667d52dffaae071 (trivial change that would not even need any CLAs).

**Comment by julianstorer** [comment]
Thanks for the heads-up, I'll get a fix pushed asap!
