### ISSUE TITLE
choc_Value.h not compatible with Clang 17/Windows

### ISSUE THREAD

**Issue by Xenakios** [Tracktion/choc#62]
The line

`__except (GetExceptionCode() == STATUS_STACK_OVERFLOW)`

causes a compilation error on Windows with Clang 17.

It first complains about the STATUS_STACK_OVERFLOW is an undeclared identifier. If I hack a hardcoded number for that, it then proceeds to complain GetExceptionCode is also an undeclared identifier.

**Comment by julianstorer** [comment]
Hmm, I don't have that compiler setup to try it. 
It could probably just be simplified to `__except (1)`, does that work for your build?

**Comment by Xenakios** [comment]
> Hmm, I don't have that compiler setup to try it. It could probably just be simplified to `__except (1)`, does that work for your build?

Yes, changing to that works, thanks!

**Comment by julianstorer** [comment]
OK, thanks, I'll push that!
