### ISSUE TITLE
WebView Memory DLL still required? 

### ISSUE THREAD

**Issue by olilarkin** [Tracktion/choc#9]
Since Microsoft [now provide instructions](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/static) about how to statically link the ICoreWebView2 loader, is the encoded dll in the choc_webview header still needed? Not sure how easy that static-link step is when you're not using a MSVS project etc.

**Comment by julianstorer** [comment]
Thanks for the heads-up about that, but I think I'll leave my horrible DLL hack in there for the time being. 

Good that MS are making it easier to link it, but it still looks like some extra faff and project wrangling to do it that way, whereas the nice thing about the choc header is that it has no build requirements at all.
